spring.application.name=fitness-application

# Server Port
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://chandan807cv:chandan807cv@cluster0.z7p61c3.mongodb.net/fitness_db?retryWrites=true&w=majority&appName=Cluster0

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chandan807cv@gmail.com
spring.mail.password=hnnx hyku awvk dmsz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OAuth2 Google Client
spring.security.oauth2.client.registration.google.client-id=275755119185-jtis8vg9u5hi7p8i17usf1pfhgodtlpl.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# JWT Configuration
jwt.secret=Qjd0zHbDUT1JG2mGUMOiHxRZUPPX+3kjQ3Zz8gEMgyk=
jwt.access-token-expiry-minutes=15
jwt.issuer=auth-app
